- name: Set GRUB timeout to 0
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_TIMEOUT='
    line: 'GRUB_TIMEOUT=0'
    state: present
    backup: true
  notify: Update GRUB
