all:
  children:
    debian:
      hosts:
        "0x3110":
          ansible_host: LOCAL_IP
          ansible_user: SSH_USER
          ansible_ssh_private_key_file: ~/.ssh/SSH_PRIVATE_KEY
          ansible_ssh_port: SSH_PORT
